FROM python:3.7

# Install pip libraries
ADD requirements-TA2.txt requirements.txt
RUN pip install -r requirements.txt

# Load objects library.
ADD source/objects /aiq-sail-on/objects/

# Load TA2.py
ADD source/TA2.py /aiq-sail-on/

# Change local dir
WORKDIR /aiq-sail-on/
